# Package Import

In [1]:
import pandas as pd 
import numpy as np

### Renaming

In [2]:
rename_dict = {
    'ISBN': 'isbn',
    'Book-Author': 'authors',
    'Book-Title': 'title',
    'Year-Of-Publication': 'original_publication_year',
    'Image-URL-S': 'small_image_url'
}

ratings_l = pd.read_csv(r"C:\Users\penna\Documents\Porta\Education\Coding\librec\librec\data_warehouse\larger_set\ratings.csv", sep = ';', encoding = 'latin-1')
users_l = pd.read_csv(r"C:\Users\penna\Documents\Porta\Education\Coding\librec\librec\data_warehouse\larger_set\users.csv", sep = ';', encoding = 'latin-1')
books_l = pd.read_csv(r"C:\Users\penna\Documents\Porta\Education\Coding\librec\librec\data_warehouse\larger_set\books.csv", sep = ';', encoding = 'latin-1', error_bad_lines=False)
books_l = books_l.rename(columns = rename_dict).drop(['Publisher', 'Image-URL-M','Image-URL-L'], axis = 1)
books_l['original_publication_year'] =  pd.to_numeric(books_l['original_publication_year'], errors='coerce', downcast='integer')

# Import smaller set
ratings_s = pd.read_csv(r"C:\Users\penna\Documents\Porta\Education\Coding\librec\librec\data_warehouse\goodbooks-10k\ratings_10k.csv")
books_s = pd.read_csv(r"C:\Users\penna\Documents\Porta\Education\Coding\librec\librec\data_warehouse\goodbooks-10k\books_10k.csv")
books_s_redux = books_s[['isbn','authors','title','original_publication_year','small_image_url']]
books_s_redux['original_publication_year'] = pd.to_numeric(books_s['original_publication_year'], errors='coerce', downcast='integer')

books_df = pd.concat([books_l, books_s_redux], axis = 0)
books_df = books_df.drop_duplicates(subset = 'isbn')

C:\Users\penna\AppData\Local\Temp\ipykernel_18228\2935986721.py:11: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  books_l = pd.read_csv(r"C:\Users\penna\Documents\Porta\Education\Coding\librec\librec\data_warehouse\larger_set\books.csv", sep = ';', encoding = 'latin-1', error_bad_lines=False)
b'Skipping line 6452: expected 8 fields, saw 9\nSkipping line 43667: expected 8 fields, saw 10\nSkipping line 51751: expected 8 fields, saw 9\n'
b'Skipping line 92038: expected 8 fields, saw 9\nSkipping line 104319: expected 8 fields, saw 9\nSkipping line 121768: expected 8 fields, saw 9\n'
b'Skipping line 144058: expected 8 fields, saw 9\nSkipping line 150789: expected 8 fields, saw 9\nSkipping line 157128: expected 8 fields, saw 9\nSkipping line 180189: expected 8 fields, saw 9\nSkipping line 185738: expected 8 fields, saw 9\n'
b'Skipping line 209388: expected 8 fields, saw 9\nSkipping line 220626: exp

In [21]:
books_df

isbn                                              title  \
0     0195153448                                Classical Mythology   
1     0002005018                                       Clara Callan   
2     0060973129                               Decision in Normandy   
3     0374157065  Flu: The Story of the Great Influenza Pandemic...   
4     0393045218                             The Mummies of Urumchi   
...          ...                                                ...   
9993   810983559          The Everafter War (The Sisters Grimm, #7)   
9994  1416523723                                 Billy Budd, Sailor   
9995   441019455                          Bayou Moon (The Edge, #2)   
9998    61711527  Cinderella Ate My Daughter: Dispatches from th...   
9999   375700455                                The First World War   

                              authors  original_publication_year  \
0                  Mark P. O. Morford                     2002.0   
1                Richard Bruce Wright                     2001.0   
2                        Carlo D'Este                     1991.0   
3                    Gina Bari Kolata                     1999.0   
4                     E. J. W. Barber                     1999.0   
...                               ...                        ...   
9993  Michael Buckley, Peter Ferguson                     2009.0   
9994                  Herman Melville                     1924.0   
9995                    Ilona Andrews                     2010.0   
9998                  Peggy Orenstein                     2011.0   
9999                      John Keegan                     1998.0   

                                        small_image_url  
0     http://images.amazon.com/images/P/0195153448.0...  
1     http://images.amazon.com/images/P/0002005018.0...  
2     http://images.amazon.com/images/P/0060973129.0...  
3     http://images.amazon.com/images/P/0374157065.0...  
4     http://images.amazon.com/images/P/0393045218.0...  
...                                                 ...  
9993  https://images.gr-assets.com/books/1388278230s...  
9994  https://s.gr-assets.com/assets/nophoto/book/50...  
9995  https://images.gr-assets.com/books/1307445460s...  
9998  https://images.gr-assets.com/books/1279214118s...  
9999  https://images.gr-assets.com/books/1403194704s...  

[280263 rows x 5 columns]

In [3]:
rating_column_dict = {
    'User-ID': 'user_id_adj',
    'ISBN': 'isbn',
    'Book-Rating': 'rating_adj'
}

ratings_s['isbn'] = ratings_s['book_id'].map(books_s[['id', 'isbn']].set_index('id').to_dict()['isbn'])
ratings_s['rating_adj'] = ratings_s['rating'] * 2
ratings_s['user_id_adj'] = ratings_s['user_id'] + ratings_l['User-ID'].max() + 1
ratings_s_redux = ratings_s[['user_id_adj', 'isbn', 'rating_adj']]
ratings_l = ratings_l.rename(columns = rating_column_dict)
ratings_df = pd.concat([ratings_l, ratings_s_redux], axis = 0)



## Check Shape

In [4]:
ratings_s.shape

(981756, 6)

In [6]:
ratings_df

user_id_adj        isbn  rating_adj
0            276725  034545104X           0
1            276726  0155061224           5
2            276727  0446520802           0
3            276729  052165615X           3
4            276729  0521795028           6
...             ...         ...         ...
981751       327241   375700455          10
981752       327862   375700455           8
981753       328238   375700455          10
981754       328979   375700455          10
981755       330183   375700455           2

[2131536 rows x 3 columns]

### Pivot Table

In [12]:
# create a pivot table of users, with isbn as columns and ratings as values

#ratings_pivot = ratings_df.iloc[0:100000].pivot_table(index = 'user_id_adj', columns = 'isbn', values = 'rating_adj', fill_value= 0).astype('Sparse[int]')

In [11]:
#ratings_pivot

isbn         0002005018  0002231115  0002232766  0002240114  000225669X  \
user_id_adj                                                               
2                     0           0           0           0           0   
7                     0           0           0           0           0   
8                     5           0           0           0           0   
9                     0           0           0           0           0   
10                    0           0           0           0           0   
...                 ...         ...         ...         ...         ...   
278846                0           0           0           0           0   
278849                0           0           0           0           0   
278851                0           0           0           0           0   
278852                0           0           0           0           0   
278854                0           0           0           0           0   

isbn         000254794  0002558122  0002740230  0006128831  0006379702  ...  \
user_id_adj                                                             ...   
2                    0           0           0           0           0  ...   
7                    0           0           0           0           0  ...   
8                    0           0           0           0           0  ...   
9                    0           0           0           0           0  ...   
10                   0           0           0           0           0  ...   
...                ...         ...         ...         ...         ...  ...   
278846               0           0           0           0           0  ...   
278849               0           0           0           0           0  ...   
278851               0           0           0           0           0  ...   
278852               0           0           0           0           0  ...   
278854               0           0           0           0           0  ...   

isbn         9782264014184  9782922145441  9788401499883  9871138016  \
user_id_adj                                                            
2                        0              0              0           0   
7                        0              0              0           0   
8                        0              0              0           0   
9                        0              0              0           0   
10                       0              0              0           0   
...                    ...            ...            ...         ...   
278846                   0              0              0           0   
278849                   0              0              0           0   
278851                   0              0              0           0   
278852                   0              0              0           0   
278854                   0              0              0           0   

isbn         9995585227  B0000BLD7X  B158991965  DITISEENSOORT  N3453124715  \
user_id_adj                                                                   
2                     0           0           0              0            0   
7                     0           0           0              0            0   
8                     0           0           0              0            0   
9                     0           0           0              0            0   
10                    0           0           0              0            0   
...                 ...         ...         ...            ...          ...   
278846                0           0           0              0            0   
278849                0           0           0              0            0   
278851                0           0           0              0            0   
278852                0           0           0              0            0   
278854                0           0           0              0            0   

isbn         O6712345670  
user

In [7]:
len(ratings_df.user_id_adj.unique())

158707

In [8]:
ratings_df = ratings_df.dropna()
len(ratings_df)

2064314

In [9]:
from scipy.sparse import csr_matrix
from pandas.api.types import CategoricalDtype

person_u = list(ratings_df.user_id_adj.unique())
thing_u = list(ratings_df.isbn.unique())

data = ratings_df['rating_adj'].tolist()
cat_type_col = CategoricalDtype(categories=thing_u, ordered=True)
cat_type_row = CategoricalDtype(categories=person_u, ordered=True)
row = ratings_df.user_id_adj.astype(cat_type_row).cat.codes
col = ratings_df.isbn.astype(cat_type_col).cat.codes
sparse_matrix = csr_matrix((data, (row, col)), shape=(len(person_u), len(thing_u)))

In [11]:
from sklearn.metrics.pairwise import cosine_similarity

# calculate similarity between each row (user x movies)
similarities_sparse = cosine_similarity(sparse_matrix, dense_output=False)


# Create user-similarity matrix

In [19]:
def top_n_idx_sparse(matrix, n):
    '''Return index of top n values in each row of a sparse matrix'''
    top_n_idx = []
    for le, ri in zip(matrix.indptr[:-1], matrix.indptr[1:]):
        n_row_pick = min(n, ri - le)
        top_n_idx.append(matrix.indices[le + np.argpartition(matrix.data[le:ri], -n_row_pick)[-n_row_pick:]])
    return top_n_idx

user_user_similar = top_n_idx_sparse(similarities_sparse, 3)

In [20]:
user_user_similar

[array([], dtype=int32),
 array([1], dtype=int32),
 array([], dtype=int32),
 array([3], dtype=int32),
 array([], dtype=int32),
 array([46077, 75674,     5], dtype=int32),
 array([6], dtype=int32),
 array([14203, 57512,     7], dtype=int32),
 array([8], dtype=int32),
 array([], dtype=int32),
 array([38540, 94885,    10], dtype=int32),
 array([77337,    11], dtype=int32),
 array([12], dtype=int32),
 array([64334,  7867,    13], dtype=int32),
 array([78187, 76019,    14], dtype=int32),
 array([15], dtype=int32),
 array([45540, 58632,    16], dtype=int32),
 array([], dtype=int32),
 array([18], dtype=int32),
 array([28310, 26762,    19], dtype=int32),
 array([14243, 67262,    20], dtype=int32),
 array([21], dtype=int32),
 array([ 5063, 29874,    22], dtype=int32),
 array([39123, 29404,    23], dtype=int32),
 array([28194, 18607,    24], dtype=int32),
 array([105239,  10111,     25], dtype=int32),
 array([89892,    26], dtype=int32),
 array([], dtype=int32),
 array([38952, 87281,    28], dty